// <auto-generated />
namespace InspectR.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class remove_requests : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_requests));
        
        string IMigrationMetadata.Id
        {
            get { return "201211100429021_remove_requests"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
