// <auto-generated />
namespace InspectR.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class inspector_datecreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inspector_datecreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201211091526417_inspector_datecreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
