// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace InspectR.Migrations
{
    public sealed partial class requestinfo_entry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(requestinfo_entry));
        
        string IMigrationMetadata.Id
        {
            get { return "201211082352151_requestinfo_entry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
