// <auto-generated />
namespace InspectR.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class bin_title : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bin_title));
        
        string IMigrationMetadata.Id
        {
            get { return "201211191018407_bin_title"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
