// <auto-generated />
namespace InspectR.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class userprofiles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userprofiles));
        
        string IMigrationMetadata.Id
        {
            get { return "201211110328459_userprofiles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
